using System.Text;

int[] seeds = [
    -2147483648,
    -2147483647,
    -2147483646,
    -161803399,
    -161803398,
    -161803397,
    0,
    1,
    2,
    3,
    69,
    187,
    420,
    1337,
    65536,
    161803397,
    161803398,
    161803399,
    2147483646,
    2147483647,
];

(int, int)[] ranges = [
    (0, 0),
    (0, 1),
    (0, 2),
    (0, 67),
    (0, 1738),
    (0, 161803398),
    (0, 2147483647),
    (-1, 0),
    (-420, 187),
    (-80085, 8008135),
    (-2147483648, 0),
    (-2147483648, 2147483647),
    (-2147469000, 2147420000),
];

int sampleCount = 6;
int byteCount = 12;

string timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");
StringBuilder sb = new();
sb.AppendLine($"//! This file was @generated by a C# script at {timestamp}.");
sb.AppendLine();
sb.AppendLine("use dotnet_rng::DotnetRng;");
sb.AppendLine();


foreach (int seed in seeds) {
    RunTest("next", "next()", seed, rng => rng.Next().ToString());
    RunTest("i64", "next_i64()", seed, rng => rng.NextInt64().ToString());
    RunTest("double", "next_f64().to_bits()", seed, rng => BitConverter.DoubleToUInt64Bits(rng.NextDouble()).ToString());
    RunTest("float", "next_f32().to_bits()", seed, rng => BitConverter.SingleToUInt32Bits(rng.NextSingle()).ToString());

    byte[] buffer = new byte[byteCount];
    RunTest("bytes", "next_bytes()", seed, rng => {
        rng.NextBytes(buffer);
        return "[" + string.Join(", ", buffer) + "]";
    });

    foreach ((int start, int end) in ranges) {
        RunTest(
            $"range_{Int2Str(start)}_to_{Int2Str(end)}",
            $"next_range({start}, {end})",
            seed,
            rng => rng.Next(start, end).ToString()
        );

        RunTest(
            $"i64_range_{Int2Str(start)}_to_{Int2Str(end)}",
            $"next_i64_range({start}, {end})",
            seed,
            rng => rng.NextInt64(start, end).ToString()
        );

        if (start == 0) {
            RunTest(
                $"max_{Int2Str(end)}",
                $"next_range(0, {end})",
                seed,
                rng => rng.Next(end).ToString()
            );

            RunTest(
                $"i64_max_{Int2Str(end)}",
                $"next_i64_range(0, {end})",
                seed,
                rng => rng.NextInt64(end).ToString()
            );
        }
    }
}

Console.WriteLine(sb);

///////////////////
string Int2Str(int number) => number.ToString().Replace("-", "neg_");

void MakeTest(ref StringBuilder sb, string name, int seed, string funcCall, string[] values) {
    sb.AppendLine("#[test]");
    sb.Append($"fn seed_{Int2Str(seed)}_");
    sb.Append(name);
    sb.AppendLine("() {");
    sb.AppendLine($"    let mut rng = DotnetRng::new({seed});");

    foreach (string value in values) {
        sb.AppendLine($"    assert_eq!(rng.{funcCall}, {value});");
    }

    sb.AppendLine("}");
    sb.AppendLine();
}

void RunTest(string name, string funcCall, int seed, Func<Random, string> sample) {
    Random rng = new(seed);
    string[] values = new string[sampleCount];
    for (int i = 0; i < sampleCount; i++) {
        values[i] = sample(rng);
    }
    MakeTest(ref sb, name, seed, funcCall, values);
}
